### ISSUE TITLE
Patcher fails with "Unknown patching strategy: 'null'." if the entered path ends in \

### ISSUE THREAD

**Issue by AdrianBuza** [oxygenxml/oxygen-log4j-patcher#10]
We had a user report a problem with the path entered to point to the Oxygen folder. If the entered path ends in "\\", the patcher fails.
e.g.
```
D:\gitProjects\oxygen-log4j-patcher>patch.bat
...
Enter path:C:\Program Files\Oxygen XML Editor 21.1\
Using java from: "C:\Program Files\Oxygen XML Editor 21.1\\jre"
Please confirm that you want to apply the patch over the folder:
"C:\Program Files\Oxygen XML Editor 21.1\"
(yes/no)yes
Please choose what type of patch do you want to apply:
  Type 'u' - for upgrading the log4j library
  Type 'r' - for keeping the current log4j library, but removing the vulnerable JNDI classes from it.
Enter one of (u/r):u
Configuration ok.
Make sure the Oxygen application or server is closed before proceeding.
Press ENTER when ready...

D:\gitProjects\oxygen-log4j-patcher>"C:\Program Files\Oxygen XML Editor 21.1\\jre\bin\java.exe" -cp target/classes com.oxygenxml.patcher.log4j.Patcher "C:\Program Files\Oxygen XML Editor 21.1\" "u"
Java version is 1.8.0_202
Unknown patching strategy: 'null'.
```

**Comment by raducoravu** [comment]
When a path like this is executed:

     "C:\Program Files\Oxygen XML Editor 22\\jre\bin\java.exe" -cp target/classes com.oxygenxml.patcher.log4j.Patcher "C:\Program Files\Oxygen XML Editor 22\" "u"

that extra \ in the first argument's path somehow means that in the Java code the args[] list receives only one argument with value "C:\Program Files\Oxygen XML Editor 22 u" instead of receiving 2 arguments, so I modified the bat file to trim that extra \ if it exists.

**Comment by raducoravu** [comment]
@AdrianBuza maybe you can double check if this works also for you
