### ISSUE TITLE
log4j still old version after appliying the patch

### ISSUE THREAD

**Issue by mricaud** [oxygenxml/oxygen-log4j-patcher#12]
Hi, I just applied the patch to my "Oxygen XML Developer 21", but it looks like there are still 2 log4j.jar files that are out of date (last modification of the file is 04/2019) :
* Oxygen XML Developer 21\lib\log4j.jar
* Oxygen XML Developer 21\frameworks\dita\DITA-OT3.x\plugins\com.oxygenxml.common\lib\log4j.jar

My IT services are complaining about that 2 files still have the log4j vulnerability.

Did I missed something?

Thanks for helping

Matthieu RICAUD-DUSSARGET

**Comment by raducoravu** [comment]
If you are using Oxygen version 22.0, those log4j libraries which do not get updated are of version 1.x which had a totally different architecture and internal code and were not affected by the log4j 2.x security problems.

**Comment by raducoravu** [comment]
Similar question was posed here: https://github.com/oxygenxml/oxygen-log4j-patcher/issues/11

**Comment by mricaud** [comment]
Hi Radu, 
I'm using 21.0 so it's okay. 
Thanks for the reply ! and sorry for not having seen the similar question
