### ISSUE TITLE
Oxygen XML Editor Datasources log4j

### ISSUE THREAD

**Issue by Kolophonium0** [oxygenxml/oxygen-log4j-patcher#2]
I dont know where to put this because its more a general question: 
The exist-db datasources (manually created) uses the log4j.jar files for exist-db connections to connect to older exist-db Versions (eg. Versions < 5) is there a need to patch these local files too?

**Comment by raducoravu** [comment]
You should probably first update your Exist server to the latest version (I think they already released new versions for this problem yesterday).
Then delete your configured data sources, delete the folder where the Jars were located and re-create them in Oxygen using the Exist DB connection wizard which brings down JAR libraries from the Exist server:

https://www.oxygenxml.com/doc/versions/24.0/ug-editor/topics/how-to-exist.html
